# ドメイン翻訳設定
domains:
  - domain: "github.com"
    name: "GitHub UI 翻訳"
    repository: "https://raw.githubusercontent.com/223n-tech/Multillingual-Website-Translation/refs/heads/master/config/translation-config-github.yml?token=GHSAT0AAAAAAC6DZFIYKLVCYWGSGZA6ORG4Z6NCM2Q"
    enabled: true
    description: "GitHub UI の日本語翻訳"
    
  # - domain: "stackoverflow.com"
  #   name: "Stack Overflow 翻訳"
  #   repository: "https://raw.githubusercontent.com/username/translations/main/stackoverflow-translations.yml"
  #   enabled: false
  #   description: "Stack Overflow の日本語翻訳"
    
  # - domain: "developer.mozilla.org"
  #   name: "MDN 翻訳"
  #   repository: "https://raw.githubusercontent.com/username/translations/main/mdn-translations.yml"
  #   enabled: false
  #   description: "Mozilla Developer Network の日本語翻訳"
