# GitHub翻訳設定ファイル
site: "github.com"
language: "日本語"
description: "GitHub UIの日本語翻訳"
version: "0.3.0"
author: "223n"
last_updated: "2025-03-09"

# 翻訳エントリー
translations:
  # ナビゲーション
  - original: "Pull requests"
    translated: "プルリクエスト"
    context: "メインナビゲーション"
    
  - original: "Issues"
    translated: "課題"
    context: "メインナビゲーション"
    
  - original: "Marketplace"
    translated: "マーケットプレイス"
    context: "メインナビゲーション"
    
  - original: "Explore"
    translated: "探索"
    context: "メインナビゲーション"
    
  # リポジトリページタブ
  - original: "Code"
    translated: "コード"
    context: "リポジトリタブ"
    
  - original: "Pull requests"
    translated: "プルリクエスト"
    context: "リポジトリタブ"
    
  - original: "Actions"
    translated: "アクション"
    context: "リポジトリタブ"
    
  - original: "Projects"
    translated: "プロジェクト"
    context: "リポジトリタブ"
    
  - original: "Wiki"
    translated: "ウィキ"
    context: "リポジトリタブ"
    
  - original: "Security"
    translated: "セキュリティ"
    context: "リポジトリタブ"
    
  - original: "Insights"
    translated: "インサイト"
    context: "リポジトリタブ"
    
  - original: "Settings"
    translated: "設定"
    context: "リポジトリタブ"

  # アクションタブ内の要素
  - original: "Workflows"
    translated: "ワークフロー"
    context: "アクションタブ"
    
  - original: "Runs"
    translated: "実行履歴"
    context: "アクションタブ"
    
  # プロジェクトタブ内の要素
  - original: "Projects (classic)"
    translated: "プロジェクト(クラシック)"
    context: "プロジェクトタブ"
    
  - original: "Projects (beta)"
    translated: "プロジェクト(ベータ)"
    context: "プロジェクトタブ"

  # プロフィール要素

  - original: "Overview"
    translated: "概要"
    context: "プロフィール"

  - original: "Repositories"
    translated: "リポジトリ"
    context: "プロフィール"
    
  - original: "Projects"
    translated: "プロジェクト"
    context: "プロフィール"
    
  - original: "Packages"
    translated: "パッケージ"
    context: "プロフィール"
    
  - original: "Stars"
    translated: "お気に入り"
    context: "プロフィール"
    
  - original: "Followers"
    translated: "フォロワー"
    context: "プロフィール"
    
  - original: "Following"
    translated: "フォロー中"
    context: "プロフィール"

  - original: "Achievements"
    translated: "実績"
    context: "特殊要素"
    
  # ボタン・アクション
  - original: "New"
    translated: "新規"
    context: "ボタン"
    
  - original: "Create"
    translated: "作成"
    context: "ボタン"
    
  - original: "Delete"
    translated: "削除"
    context: "ボタン"
    
  - original: "Edit"
    translated: "編集"
    context: "ボタン"
    
  - original: "Save"
    translated: "保存"
    context: "ボタン"
    
  - original: "Cancel"
    translated: "キャンセル"
    context: "ボタン"
    
  - original: "Fork"
    translated: "フォーク"
    context: "ボタン"
    
  - original: "Star"
    translated: "お気に入り"
    context: "ボタン"
    
  - original: "Watch"
    translated: "ウォッチ"
    context: "ボタン"

  - original: "Edit profile"
    translated: "プロフィールを編集"
    context: "ボタン"

  # 特殊なテキスト（スペース処理の問題に対応）
  - original: "Actions"
    translated: "アクション"
    context: "特殊要素"
    
  - original: "Projects"
    translated: "プロジェクト"
    context: "特殊要素"
    
  - original: " Actions"  # 先頭にスペースがある場合
    translated: "アクション"
    context: "特殊要素"
    
  - original: " Projects"  # 先頭にスペースがある場合
    translated: "プロジェクト" 
    context: "特殊要素"
    
  # 正規表現パターンによる翻訳（新機能）
  - original: "Issue #(\\d+)"
    translated: "課題 #$1"
    context: "課題表示"
    regex: true
    
  - original: "(\\d+) commits?"
    translated: "$1 コミット"
    context: "コミット数"
    regex: true
    
  - original: "(\\d+) contributions? in the last year"
    translated: "昨年の貢献数: $1"
    context: "プロフィールページ"
    regex: true
    
  - original: "([A-Za-z0-9_-]+)/([A-Za-z0-9_-]+)#(\\d+)"
    translated: "$1/$2 課題#$3"
    context: "課題リファレンス"
    regex: true
    
  - original: "Created (\\d+) days? ago"
    translated: "$1 日前に作成"
    context: "日時表示"
    regex: true
    
  - original: "Last updated (\\w+ \\d+, \\d+)"
    translated: "最終更新: $1"
    context: "日時表示"
    regex: true
    
  - original: "Copy path"
    translated: "パスをコピー"
    context: "ファイルメニュー"
    
  - original: "Copy permalink"
    translated: "永続リンクをコピー"
    context: "ファイルメニュー"
